Dsn: root:1234567@tcp(127.0.0.1:3306)/
MaxIdleConn: 11
MaxOpenConn: 51
Services:
- Service:
    Dbname: dbconfig_service1
    Password: dbconfig-service1-secret
    Tables: dbconfig-service1-configmap
    User: dbconfig_service1
    rebuild: true
- Service:
    Dbname: dbconfig_service2
    Password: dbconfig-service2-secret
    Tables: dbconfig-service2-configmap
    User: dbconfig_service2
    rebuild: true
- Service:
    Dbname: dbconfig_service3
    Password: dbconfig-service3-secret
    Tables: dbconfig-service3-configmap
    User: dbconfig_service3
    rebuild: false
