Dsn: root:123456@tcp(127.0.0.1:3306)/
MaxIdleConn: 10
Services:
- Service:
    Dbname: test
    Password: test-db-password
    Tables: test-db-table
    User: testuser
    rebuild: false
- Service:
    Dbname: test1111
    Password: test-db-password
    Tables: test-db-table
    User: testuser1111
    rebuild: false
- Service:
    Dbname: mytest
    Password: test-db-password
    Tables: test-db-table-example
    User: myuser
    rebuild: true
