apiVersion: api.practice.com/v1alpha1
kind: DbConfig
metadata:
  name: mydbconfig
spec:
  dsn: root:123456@tcp(127.0.0.1:3306)/
  maxIdleConn: 10
  services:
    - service:
        user: testuser             # 用户名
        password: test-db-password # secret 名，用于db用户的密码，用户需要先创建secret资源，并在此指定
        dbname: test               # db名
        tables: test-db-table      # configmap名，用于创建表，用户需要先创建configmap资源，并在此指定
    - service:
        user: testuser1111
        password: test-db-password
        dbname: test1111
        tables: test-db-table
    - service:
        user: myuser
        password: test-db-password
        dbname: mytest
        tables: test-db-table-example

